Don't test Python 2.7 on macOS
It looks like 2.7 doesn't exist anymore:

    Error: Version 2.7 with arch x64 not found
    Available versions:

    3.10.0 (x64)
    3.7.12 (x64)
    3.8.12 (x64)
    3.9.7 (x64)

https://github.com/JuliaPy/PyCall.jl/runs/3986093438?check_suite_focus=true